# -*- mode: org; org-confirm-babel-evaluate: nil -*-

#+TITLE: Incompact3D Case Definition: Taylor-Green Vortex
#+AUTHOR: Paul Bartholomew

#+STARTUP: inlineimages
#+OPTIONS: toc:nil

#+LATEX_CLASS_OPTIONS: [a4paper, 10pt]
#+LATEX_HEADER: \usepackage{fullpage}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \fvset{fontsize=\footnotesize}
#+LATEX_HEADER: \RecustomVerbatimEnvironment{verbatim}{Verbatim}{xleftmargin=5mm, samepage=true}
#+LATEX_HEADER: \hypersetup{colorlinks, linkcolor=red, urlcolor=blue}

#+BEGIN_ABSTRACT
This document is the case definition file for Incompact3D, it is a literate program written in Emacs
org-mode and is intended simplify access to user-facing aspects of the Incompact3D Navier-Stokes
solver.
To setup a case, edit this document as appropriate - for example change the size of the mesh by
editing the numbers in mesh size - then run ~make tangle~ to ``tangle'' these changes into the
Incompact3D source code, followed by ~make build~ to compile these changes.

*N.B.* This is not intended to document Incompact3D itself but the setup of a case in the hope of
 facilitating reproducibility of the simulation.
The user is encouraged to write what they are simulating as part of this document.
#+END_ABSTRACT

#+TOC: headlines 2

* Case Description

This case definition file is for a 3D channel flow simulation.

#+BEGIN_LATEX
  \pagebreak
#+END_LATEX

* Basic Configuration

** Name

Here you can name the case:

#+NAME: name
#+BEGIN_SRC text
# - 3D Taylor-Green Vortex -
#+END_SRC

** Domain

*** Size

Here you can define the domain, variables:
- ~xlx~: ~float~ the extent of the domain in the x-direction
- ~yly~: ~float~ the extent of the domain in the y-direction
- ~zlz~: ~float~ the extent of the domain in the z-direction

#+NAME: domain
#+BEGIN_SRC text
6.28    # xlx
6.28    # yly
6.28    # zlz
#+END_SRC

*** Decomposition

Here you can specify the domain decomposition, variables:
- ~p_row~: ~int~
- ~p_col~: ~int~
setting both to zero will have Incompact3D try to determine the ideal decomposition automatically.

#+NAME: decomp
#+BEGIN_SRC text
0 # p_row
0 # p_col
#+END_SRC

#+BEGIN_LATEX
  \pagebreak
#+END_LATEX

** Mesh

Here you can define the mesh parameters, variables are:
- ~nx~: ~int~ number of nodes in x direction
- ~ny~: ~int~ number of nodes in y direction
- ~nz~: ~int~ number of nodes in z direction
- ~istret~: ~int~ y mesh refinement
  - 0: no refinement
  - 1: centre
  - 2: both
  - 3: bottom
- ~beta~: ~float~ stretching parameter

#+NAME: nnodes
#+BEGIN_SRC text
128    # nx
128    # ny
128    # nz
#+END_SRC

#+NAME: stretching
#+BEGIN_SRC text
0    # istret
0.0  # beta
#+END_SRC
** Fluid

#+NAME: fluid
#+BEGIN_SRC text :noweb yes :exports none
  #
  # Incompact 3D Fluid
  #
  <<fluid_prop>>
#+END_SRC

*** Properties

#+NAME: fluid_prop
#+BEGIN_SRC text
5000.0  # Reynolds number
#+END_SRC

*** Boundary conditions

**** Boundary types

**** Boundary functions

** Scalar

#+NAME: scalar
#+BEGIN_SRC text :noeweb yes :exports none
  #
  # Incompact 3D Scalar
  #
  <<nscalar>>
#+END_SRC

#+NAME: nscalar
#+BEGIN_SRC text
  0 # nscalar
#+END_SRC

** Time Integration

#+NAME: time
#+BEGIN_SRC text
0.0005 # dt
1      # nscheme
40000  # ilast
#+END_SRC

** Initialisation

#+NAME: init
#+BEGIN_SRC text
#+END_SRC

* Advanced Configuration

** Numerical dissipation

Here you can set the options for numerical dissipation, variables are:
- ~jLES~: ~int~ select the LES model:
  - 0: DNS
  - 1: iLES
  - 2: Explicit Simple Smagorinsky
  - 3: Explicit Wall-Adaptive LES
  - 4: Explicit Dynamic Smagorinsky LES
- ~npi2~: ~float~

#+NAME: dissipation
#+BEGIN_SRC text
0   # jLES
4.0 # npi2
#+END_SRC

#+BEGIN_LATEX
  \pagebreak
#+END_LATEX
* Post Processing

#+BEGIN_LATEX
  \pagebreak
#+END_LATEX
* incompact3d.prm
# This code-block generates the file ~incompact3d.prm~ - hopefully you won't have to edit it.

The generated incompact3d.prm is:

#+NAME: incompact3d.prm
#+BEGIN_SRC text :noweb yes :tangle incompact3d.prm
  ##############################################################
  #
  # INCOMPACT 3D parameters - Generated by Incompact3D case.org
  #
  ##############################################################
  #
  # Domain + mesh
  #
  <<domain>>
  <<nnodes>>
  <<stretching>>
  <<decomp>>
  <<fluid>>
  <<scalar>>
  <<numerics>>
  <<run>>
#+END_SRC

#+NAME: numerics
#+BEGIN_SRC text :noweb yes :exports none
#
# Incompact 3D Numerics
#
<<time>>
<<dissipation>>
#+END_SRC

#+NAME: gred
#+BEGIN_SRC text :noweb yes :exports none
  #
  # Incompact 3D Domain + Mesh
  #
  <<domain>>
  <<nnodes>>
  <<stretching>>
  <<decomp>>
#+END_SRC

#+BEGIN_LATEX
  \pagebreak
#+END_LATEX

* Source Code                                                      :noexport:

This section contains the source code to be tangled into Incompact3D - it should not generally be edited.
